local options = {
	char = "│",
	show_current_context = true,
	show_first_indent_level = true,
	use_treesitter = true,
	indentLine_enabled = 1,
	show_trailing_blankline_indent = false,
	filetype_exclude = {
		"help",
		"terminal",
		"lazy",
		"lspinfo",
		"TelescopePrompt",
		"TelescopeResults",
		"mason",
		"NvimTree",
		"dashboard",
		"Trouble",
		"",
	},
	buftype_exclude = {
		"terminal",
	},
	-- context_patterns = {
	--   "class",
	--   "return",
	--   "function",
	--   "method",
	--   "^if",
	--   "^while",
	--   "jsx_element",
	--   "^for",
	--   "^object",
	--   "^table",
	--   "block",
	--   "arguments",
	--   "if_statement",
	--   "else_clause",
	--   "jsx_element",
	--   "jsx_self_closing_element",
	--   "try_statement",
	--   "catch_clause",
	--   "import_statement",
	--   "operation_type",
	-- }
}

return options
